add_newline = true
command_timeout = 500

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[hostname]
ssh_only = false
format = "[$hostname](bold yellow) in "

[kubernetes]
format = "on [☸ $context ($namespace)](bold red) "
disabled = false

[nodejs]
format = "via [ $version](bold green) "

[python]
format = "via [🐍 $version](bold yellow) "

[terraform]
format = "via [💠 $workspace](bold purple) "

[aws]
format = "on [☁️ $profile($region)](bold yellow) "

[gcloud]
format = "on [☁️ $project](bold blue) "

[git_branch]
format = "on [$symbol$branch](bold purple) "

[git_status]
format = "[$all_status$ahead_behind](bold green) "

[cmd_duration]
format = "took [$duration](bold yellow) "
min_time = 2000

[directory]
truncation_length = 3
